# Generated by Django 3.2.4 on 2021-06-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20210623_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='fk_atendente',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='fk_cliente',
        ),
        migrations.AddField(
            model_name='chamado',
            name='atendente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.atendente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.cliente'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Andamento'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='chamado_interacao',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
