# Generated by Django 3.2.4 on 2021-06-23 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0003_chamado_chamado_interacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='username',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
        migrations.AddField(
            model_name='atendente',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
