# Generated by Django 3.2.4 on 2021-06-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_auto_20210624_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='atendente',
            new_name='fk_atendente',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='cliente',
            new_name='fk_cliente',
        ),
    ]
