# Generated by Django 3.2.4 on 2021-06-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_auto_20210623_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='fk_atendente',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='fk_cliente',
        ),
    ]
