# Generated by Django 3.2.4 on 2021-06-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_auto_20210623_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='fk_atendente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='helpdesk.atendente'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='fk_cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='helpdesk.cliente'),
        ),
    ]
