# Generated by Django 3.2.4 on 2021-06-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_auto_20210624_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendente',
            old_name='user',
            new_name='user_atendente',
        ),
    ]
