# Generated by Django 3.2.4 on 2021-06-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_rename_user_atendente_user_atendente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendente',
            old_name='user_atendente',
            new_name='user',
        ),
    ]
